// File generated by FlutterFire CLI.
// This is a template file. You need to run 'flutterfire configure' to generate the actual file.
// Or manually add your Firebase configuration here.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZSuohsKSt_QSwz15o3KOoYciBQfjiG8',
    appId: '1:386991008585:web:ea8262aeb3e4088e928898',
    messagingSenderId: '386991008585',
    projectId: 'instatest-78475',
    authDomain: 'instatest-78475.firebaseapp.com',
    storageBucket: 'instatest-78475.firebasestorage.app',
    measurementId: 'G-7L3X1SG5CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDIjmX8dVnuHtYJ3zWQCf_1IoWz5aIwg',
    appId: '1:386991008585:android:55d8cb6d3987bab8928898',
    messagingSenderId: '386991008585',
    projectId: 'instatest-78475',
    storageBucket: 'instatest-78475.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr_C5ci4pciYLAbf3rg6dYQfZ5Ecz4CpY',
    appId: '1:386991008585:ios:6f7ecca72cbacc0c928898',
    messagingSenderId: '386991008585',
    projectId: 'instatest-78475',
    storageBucket: 'instatest-78475.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr_C5ci4pciYLAbf3rg6dYQfZ5Ecz4CpY',
    appId: '1:386991008585:ios:6f7ecca72cbacc0c928898',
    messagingSenderId: '386991008585',
    projectId: 'instatest-78475',
    storageBucket: 'instatest-78475.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZSuohsKSt_QSwz15o3KOoYciBQfjiG8',
    appId: '1:386991008585:web:4eed0c3300f4f123928898',
    messagingSenderId: '386991008585',
    projectId: 'instatest-78475',
    authDomain: 'instatest-78475.firebaseapp.com',
    storageBucket: 'instatest-78475.firebasestorage.app',
    measurementId: 'G-ZED2YY0LP6',
  );

}